#!/bin/bash
#
# VERY basic init-like script for starting and stopping all configured servers

echo $0 $@ >> /tmp/mcss.log

ALL_SERVERS=0

ARGS=$(getopt -o a -l all -- "$@")
eval set -- "${ARGS}"

while true ; do
  case "$1" in
    -a|--all)
      ALL_SERVERS=1
      shift
      ;;
    --) shift ; break ;;
    *) exit 1 ;;
  esac
done

function iterate_servers()
{
  export DAEMON=1
  if [ ! -f /etc/mcss.d/*.conf ]; then
    echo "No minecraft servers configured"
    echo "Place configuration files in /etc/mcss.d and restart mcss"
  else
    for f in /etc/mcss.d/*.conf; do
      . $f
      if [[ ${DISABLED} == 0 ]]; then
        echo "  "$(basename $f .conf)
        case $1 in
          start)
            if [[ ${AUTOSTART} == 1  || ${ALL_SERVERS} == 1 ]]; then
              mcss ${SERVER_PATH} $1 $2 "$@"
            fi
            ;;
          *)
            mcss ${SERVER_PATH} $1 $2 "$@"
        esac
        #Check for failed start
      fi
    done
  fi
}

case $1 in
  start|stop|restart|backup)
    iterate_servers $1
    ;;
  warn-stop|warn-restart)
    echo "Servers will stop/restart in 15 minutes."
    iterate_servers $1 -q
    ;;
  list)
    export SCREENDIR=/var/lib/mcss
    screen -list
    ;;
  *)
    echo "Unknown command.  Valid commands: start, stop, backup, restart, warn-stop, warn-restart"
    exit 2
    ;;
esac

exit 0
