#!/bin/bash
#
# /etc/init.d/mcss
# VERY basic init-like script for starting and stopping all configured servers
#
# chkconfig: 2345 95 05
# description: Minecraft Servers
#
# processname: mcss
# config: /etc/mcss.conf

case $1 in
  start|stop|restart|backup|warn-stop|warn-restart)
    mcssd $1
    ;;
  *)
    echo "Unknown command.  Valid commands: start, stop, backup, restart, warn-stop, warn-restart"
    exit 1
    ;;
esac

exit 0
